Extend support for event clauses to global, pool and pool6
voxpupuli/puppet-dhcp pull request #252
Opened 2021-02-17 13:01 UTC by mergwyn

#### Pull Request (PR) description
The event handlers are currently only supported for dhcp::host (see #216). These handlers can also exist globally in dhcpd.conf or in the pool definition dhcpd::pool and dhcpd::pool6. This PR extends support to these cases

#### This Pull Request (PR) fixes the following issues
Fixes #251

2021-02-17 19:50 UTC, kenyon approved these changes

2021-10-30 09:48 UTC, mergwyn commented
Many apologies - I thought I had added a comment about the CentOS6 tests failing, but clearly had not, and then I forgot all about it!

Rebasing my branch fixed the test issues, but resulted in rubocop errors which I have now fixed and then squashed.  Hopefully, this PR is now in a state where we can proceed.

2021-10-31 17:27 UTC, kenyon requested changes

2021-10-31 17:27 UTC, kenyon commented on spec/classes/dhcp_spec.rb
> +    context 'when event claused defined' do
```suggestion
    context 'when event clauses defined' do
```

2021-10-31 18:10 UTC, mergwyn commented
Changes made!

2021-10-31 18:15 UTC, kenyon approved these changes

2021-10-31 18:16 UTC, merged